#query to get all issues showing total, open, and closed

query {
    repository(owner:"rropen", name:"MEC") {
        issues {
            totalCount
        }
        open: issues(states:OPEN) {
            totalCount
        }
        closed: issues(states:CLOSED){
            totalCount
        }
    }
}




